import { defineConfig } from "tsdown";

export default defineConfig({
  entry: ["src/index.ts", "src/icons/index.ts"],
  format: ["esm", "cjs"],
  dts: {
    resolver: "oxc",
  },
  // dist/style.css is generated by the prebuild script (scripts/build-css.mjs)
  // before tsdown runs; publint (below) checks it exists, so tsdown must not
  // wipe it out.
  clean: false,
  deps: {
    neverBundle: ["react", "react-dom"],
  },
  publint: true,
});